AllCops:
  NewCops: enable

Style/AccessorGrouping:
  Enabled: true
  EnforcedStyle: separated

Style/StringLiterals:
  EnforcedStyle: double_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*/schema.rb'
