AllCops:
  NewCops: enable

Layout/LineLength:
  Max: 80

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*/schema.rb'

Style/AccessorGrouping:
  Enabled: true
  EnforcedStyle: separated

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes
